stages:
  - deploy

deploy_to_server:
  stage: deploy
  only:
    - dev_akash
  script:
    - ssh parikshit@115.166.142.18 "cd /home/parikshit/nabnext/nabnext && sudo git pull && sudo npm install && sudo npm build && npm run start"
