image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  script:
    - npm install # or "yarn install" if using Yarn
    - npm run build # or "yarn build" if using Yarn
  artifacts:
    paths:
      - .next/ # The directory where Next.js builds the application
  only:
    - stage
