stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy:
  image: docker:dind
  stage: deploy
  script:
    - docker build -t nabnext .
    - docker run -d -p 3000:3000 --rm --name next-blog nabnext
  tags:
    - docker
  only:
    - dev_akash   # Change this line to the desired branch name, e.g., dev_akash
