image: node:14

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next/
  only:
    - stage

deploy:
  stage: deploy
  script:
    - echo "Deploying to the server"
    - sshpass -p $SSH_PASS ssh $SSH_USER@$SSH_HOST 'cd /home/parikshit/nabnext/nabnext && git fetch && git checkout dev_akash && git pull && npm install && npm run build && npm run start'
  only:
    - stage
