image: node:latest

stages:
  - build
  - deploy

before_script:
  - echo "Installing dependencies..."
  - npm install

build:
  stage: build
  script:
    - echo "Building project..."
    - npm run build

deploy:
  stage: deploy
  script:
    - echo "Deploying project..."
    - ssh parikshit@115.166.142.18 "cd /home/parikshit/nabnext/nabnext && npm install && npm run start"