# .gitlab-ci.yml

image: node:14

variables:
  NODE_ENV: "production"

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm run start
  artifacts:
    paths:
      - .next/ # Change this to your Next.js build output directory
  only:
    - dev_akash # Change this to the branch you want to trigger the build

deploy:
  stage: deploy
  script:
    - sshpass -p "lpa24div@1Best" scp -o StrictHostKeyChecking=no .next/* parikshit@115.166.142.18:/var/www/nextjs_app/ # Change this to your server details and desired deployment directory
  only:
    - dev_akash # Change this to the branch you want to trigger the deployment
