image: node:latest

cache:
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/
    - build/

stages:
  - build
  - deploy

build:
 stage: build
 script:
  - rm -rf node_modules
  - rm -rf package-lock.json
  - npm install
  - unset CI
  - ng build --prod
  - cp -r /home/gitlab-runner/builds/JTV5LKNi/0/rajeshv/mahavikreta-frontend/dist/* /home/gitlab-runner/mahavikreta/
 only:
  - stage

#deploy:
# stage: deploy
# script:
#  - sudo scp -r -o StrictHostKeyChecking=no /home/gitlab-runner/mahavikreta parikshit@103.21.52.30:/tmp
#  - ssh parikshit@103.21.52.30 'sudo cp -r /tmp/mahavikreta/* /home/parikshit/mahavikreta/apache-tomcat-9.0.45/webapps/ROOT/'
# only:
#  - stage
